# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Push to gh-pages
      shell: bash
      run: git push origin master:gh-pages --force
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package -P document --file pom.xml
    - name: Commit to gh-pages
      shell: bash
      run: |
        git add .
        git commit --author="Github Action <m.petrenyi@gmail.com>" -m "Auto generate documentation"
        git push origin gh-pages --force
