# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Deploy documentation
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Push to gh-pages
      shell: bash
      run: git push origin master:gh-pages --force
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate docs with Maven
      run: mvn asciidoctor:process-asciidoc
    - name: Commit to gh-pages
      shell: bash
      run: |
        git config --global user.email "m.petrenyi@gmail.com"
        git config --global user.name "Github Action"
        git add .
        git commit -m "Add auto-generated documentation"
        git push origin gh-pages --force
